import type { Config } from "tailwindcss";

const config: Config = {
  content: [
    "./pages/**/*.{js,ts,jsx,tsx,mdx}",
    "./components/**/*.{js,ts,jsx,tsx,mdx}",
    "./app/**/*.{js,ts,jsx,tsx,mdx}",
  ],
  theme: {
    extend: {
      colors: {
        // Custom Lu.ma palette
        cranberry: {
          5: "var(--cranberry-5)",
          10: "var(--cranberry-10)",
          20: "var(--cranberry-20)",
          30: "var(--cranberry-30)",
          40: "var(--cranberry-40)",
          50: "var(--cranberry-50)",
          60: "var(--cranberry-60)",
          70: "var(--cranberry-70)",
          80: "var(--cranberry-80)",
          90: "var(--cranberry-90)",
        },
        barney: {
          5: "var(--barney-5)",
          10: "var(--barney-10)",
          20: "var(--barney-20)",
          30: "var(--barney-30)",
          40: "var(--barney-40)",
          50: "var(--barney-50)",
          60: "var(--barney-60)",
          70: "var(--barney-70)",
          80: "var(--barney-80)",
          90: "var(--barney-90)",
        },
        purple: {
          5: "var(--purple-5)",
          10: "var(--purple-10)",
          20: "var(--purple-20)",
          30: "var(--purple-30)",
          40: "var(--purple-40)",
          50: "var(--purple-50)",
          60: "var(--purple-60)",
          70: "var(--purple-70)",
          80: "var(--purple-80)",
          90: "var(--purple-90)",
        },
        blue: {
          5: "var(--blue-5)",
          10: "var(--blue-10)",
          20: "var(--blue-20)",
          30: "var(--blue-30)",
          40: "var(--blue-40)",
          50: "var(--blue-50)",
          60: "var(--blue-60)",
          70: "var(--blue-70)",
          80: "var(--blue-80)",
          90: "var(--blue-90)",
        },
        green: {
          5: "var(--green-5)",
          10: "var(--green-10)",
          20: "var(--green-20)",
          30: "var(--green-30)",
          40: "var(--green-40)",
          50: "var(--green-50)",
          60: "var(--green-60)",
          70: "var(--green-70)",
          80: "var(--green-80)",
          90: "var(--green-90)",
        },
        yellow: {
          5: "var(--yellow-5)",
          10: "var(--yellow-10)",
          20: "var(--yellow-20)",
          30: "var(--yellow-30)",
          40: "var(--yellow-40)",
          50: "var(--yellow-50)",
          60: "var(--yellow-60)",
          70: "var(--yellow-70)",
          80: "var(--yellow-80)",
          90: "var(--yellow-90)",
        },
        orange: {
          5: "var(--orange-5)",
          10: "var(--orange-10)",
          20: "var(--orange-20)",
          30: "var(--orange-30)",
          40: "var(--orange-40)",
          50: "var(--orange-50)",
          60: "var(--orange-60)",
          70: "var(--orange-70)",
          80: "var(--orange-80)",
          90: "var(--orange-90)",
        },
        red: {
          5: "var(--red-5)",
          10: "var(--red-10)",
          20: "var(--red-20)",
          30: "var(--red-30)",
          40: "var(--red-40)",
          50: "var(--red-50)",
          60: "var(--red-60)",
          70: "var(--red-70)",
          80: "var(--red-80)",
          90: "var(--red-90)",
        },
        gray: {
          10: "var(--gray-10)",
          20: "var(--gray-20)",
          30: "var(--gray-30)",
          40: "var(--gray-40)",
          50: "var(--gray-50)",
          60: "var(--gray-60)",
          70: "var(--gray-70)",
          80: "var(--gray-80)",
          90: "var(--gray-90)",
          100: "var(--gray-100)",
        },
        // ShadCN semantic colors
        background: "var(--background)",
        foreground: "var(--foreground)",
        card: {
          DEFAULT: "var(--card)",
          foreground: "var(--card-foreground)",
        },
        popover: {
          DEFAULT: "var(--popover)",
          foreground: "var(--popover-foreground)",
        },
        primary: {
          DEFAULT: "var(--primary)",
          foreground: "var(--primary-foreground)",
        },
        secondary: {
          DEFAULT: "var(--secondary)",
          foreground: "var(--secondary-foreground)",
        },
        muted: {
          DEFAULT: "var(--muted)",
          foreground: "var(--muted-foreground)",
        },
        accent: {
          DEFAULT: "var(--accent)",
          foreground: "var(--accent-foreground)",
        },
        destructive: {
          DEFAULT: "var(--destructive)",
          foreground: "var(--destructive-foreground)",
        },
        border: "var(--border)",
        input: "var(--input)",
        ring: "var(--ring)",
      },
      borderRadius: {
        lg: "var(--radius)",
        md: "calc(var(--radius) - 2px)",
        sm: "calc(var(--radius) - 4px)",
      },
      spacing: {
        xs: "var(--spacing-xs)",
        1: "var(--spacing-1)",
        2: "var(--spacing-2)",
        2.5: "var(--spacing-25)",
        3: "var(--spacing-3)",
        4: "var(--spacing-4)",
        4.5: "var(--spacing-45)",
        5: "var(--spacing-5)",
      },
      maxWidth: {
        content: "var(--max-width)",
        wide: "var(--max-width-wide-page)",
        "extra-wide": "var(--max-width-extra-wide-page)",
      },
    },
  },
  plugins: [],
};

export default config;