export enum TRPCErrorCodes {
	// Auth errors
	UNAUTHORIZED = 'UNAUTHORIZED',
	FORBIDDEN = 'FORBIDDEN',

	// Resource errors
	NOT_FOUND = 'NOT_FOUND',
	ALREADY_EXISTS = 'ALREADY_EXISTS',

	// Business logic errors
	EVENT_FULL = 'EVENT_FULL',
	ALREADY_REGISTERED = 'ALREADY_REGISTERED',
	ALREADY_MEMBER = 'ALREADY_MEMBER',

	// System errors
	VALIDATION_ERROR = 'VALIDATION_ERROR',
	INTERNAL_ERROR = 'INTERNAL_ERROR',
	EXTERNAL_SERVICE_ERROR = 'EXTERNAL_SERVICE_ERROR',
}
